name: pipeline

on: [push, pull_request]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            name: cabal-gild-x86_64-apple-darwin
            archive: cabal-gild-x86_64-apple-darwin.tar.gz
          - target: aarch64-apple-darwin
            os: macos-14
            name: cabal-gild-aarch64-apple-darwin
            archive: cabal-gild-aarch64-apple-darwin.tar.gz
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.1"
          cabal-version: "3.10"

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-
            ${{ runner.os }}-ghc-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Build
        run: cabal build all

      - name: Prepare build artifacts
        run: |
          mkdir dist
          cp $(cabal list-bin cabal-gild) ${{ matrix.name }}
          tar czvf ${{ matrix.archive }} ${{ matrix.name }}

      - name: Check codesign
        if: matrix.target == 'aarch64-apple-darwin'
        run: codesign -d -vvv ${{ matrix.name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}

  github_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: cabal-gild-x86_64-apple-darwin.tar.gz
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: cabal-gild-aarch64-apple-darwin.tar.gz
          path: .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cabal-gild-x86_64-apple-darwin.tar.gz
            cabal-gild-aarch64-apple-darwin.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
